### PR TITLE
fix: apply cluster-scoped exceptions to manual controls

### LINKED ISSUE #1893: Exceptions on manual controls not possible?!
# Description
I am not able to create an exception for the manual controls added by the PR https://github.com/kubescape/regolibrary/pull/675 to the cis framework.
I was not able to exclude the controls with the following exception specification (see below).
If this is an exception misconfiguration on my side, please let me know how the exception must be specified to exclude the mentioned controls.

# Environment
OS: `latest version of debian bookworm-slim and other linux distros`
Version: `several versions (e.g. 3.0.37 or 3.0.45)` 
 
# Steps To Reproduce

1. Scan a kubernetes cluster with kubescape using the cis framework https://github.com/kubescape/regolibrary/blob/master/frameworks/cis-v1.10.0.json
2. The results show a summary with a compliance score of less than 100% but 0 failed resources (the scans before the merge of the above mentioned pr showed a compliance score of 100%). Five control names indicate `Action Required *`, referencing the manual review
3. Adding the following kubescape exception definition, result in the same output (no change)
```
[
    {
        "name": "exception",
        "policyType": "postureExceptionPolicy",
        "actions": [
            "alertOnly"
        ],
        "resources": [
            {
                "designatorType": "Attributes",
                "attributes": {
                    "cluster": ".*"
                }
            }
        ],
        "posturePolicies": [
            {
                "controlID": "C-0286"
            },
            {
                "controlID": "C-0287"
            },
            {
                "controlID": "C-0288"
            },
            {
                "controlID": "C-0289"
            },
            {
                "controlID": "C-0246"
            },
        ]
    }
]
```

# Expected behavior
Compliance score 100% and no messages `Action Required *` in the kubescape scan summary

# Actual Behavior
Exactly as described in point 2 of steps to reproduce

### PR DESCRIPTION
**Pull request by RohanKaran**
## Overview

Exceptions for manual controls were silently ignored. Manual controls produce no resource results so the normal exception loop never processes them.

This PR adds `applyExceptionsToManualControls` which runs after the resource loop and applies exceptions directly on the control summary. Key behaviors:

- Only exceptions that explicitly name the controlID are matched (avoids system exceptions like "exclude kube-system" incorrectly marking manual controls as w/exceptions)
- Cluster designators are respected — a prod-scoped exception does not apply to dev
- Regex cluster names and regex controlIDs are supported
- Designators with namespace/name/kind/labels/WLID constraints are skipped — manual controls have no workload to match them against
- Exceptions with no `Resources` field apply globally

Why `passed + w/exceptions` instead of `skipped + w/exceptions`:
`skipped + w/exceptions` is not a valid state in the status model. `passed + w/exceptions` is already recognized and `GetControlComplianceScore` returns 100 for it.

Depends on kubescape/opa-utils#165 for `MatchesCluster` and `RegexCompareControlID` helpers. The `replace` directive in `go.mod` can be swapped for the released version once that merges.

## How to Test

```
kubescape scan framework cis-v1.10.0 --exceptions exceptions.json
# C-0246, C-0286-C-0289 → passed + w/exceptions

kubescape scan framework cis-v1.10.0
# C-0246, C-0286-C-0289 → manual review (system exceptions don't affect them)
```

## Related issues/PRs

- Resolves #1893
- Depends on kubescape/opa-utils#165

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: core/pkg/opaprocessor/processorhandlerutils.go [hunk 1]
```diff
@@ -67,12 +69,60 @@ func (opap *OPAProcessor) updateResults(ctx context.Context) {
 		opap.ResourcesResult[i] = t
 	}
 
+	// manual controls have no resource results, so exceptions must be applied directly on the summary.
+	applyExceptionsToManualControls(opap.Report.SummaryDetails.Controls, opap.Exceptions)
```
Comment (matthyx) [inline core/pkg/opaprocessor/processorhandlerutils.go]: Right now this only updates `SummaryDetails.Controls`, but each framework keeps its own `ControlSummary` copies. That leaves framework-level compliance/export out of sync. I'd pass the full `SummaryDetails` here and have `applyExceptionsToManualControls` update both the top-level controls map and every `summaryDetails.Frameworks[i].Controls` map.

```suggestion
applyExceptionsToManualControls(&opap.Report.SummaryDetails, opap.Exceptions)
```

Something along these lines in the helper keeps the copies consistent:

```go
func applyExceptionsToManualControls(summaryDetails *reportsummary.SummaryDetails, exceptionPolicies []armotypes.PostureExceptionPolicy) {
    if len(exceptionPolicies) == 0 {
        return
    }

    applyExceptionsToControlSummaries(summaryDetails.Controls, exceptionPolicies)

    for i := range summaryDetails.Frameworks {
        applyExceptionsToControlSummaries(summaryDetails.Frameworks[i].Controls, exceptionPolicies)
    }
}
```

**Comment by RohanKaran** [comment]
@matthyx switched to `passed + w/exceptions` and updated both `SummaryDetails.Controls` and each framework's Controls map.

**Review by matthyx — COMMENTED** [review]
I think the remaining gap is that the manual-control path no longer preserves the normal `Resources` / `clusterName` scoping. Right now any exception that explicitly names a manual control ID will flip it, even if the designator only targets a different cluster.

Suggested edits in `core/pkg/opaprocessor/processorhandlerutils.go`:

```diff
@@
-applyExceptionsToManualControls(&opap.Report.SummaryDetails, opap.Exceptions)
+applyExceptionsToManualControls(&opap.Report.SummaryDetails, opap.Exceptions, opap.clusterName)
@@
 func applyExceptionsToManualControls(
 summaryDetails *reportsummary.SummaryDetails,
 exceptionPolicies []armotypes.PostureExceptionPolicy,
+clusterName string,
 ) {
@@
-applyExceptionsToControlSummaries(summaryDetails.Controls, exceptionPolicies)
+applyExceptionsToControlSummaries(summaryDetails.Controls, exceptionPolicies, clusterName)
 
 for i := range summaryDetails.Frameworks {
-applyExceptionsToControlSummaries(summaryDetails.Frameworks[i].Controls, exceptionPolicies)
+applyExceptionsToControlSummaries(summaryDetails.Frameworks[i].Controls, exceptionPolicies, clusterName)
 }
 }
@@
 func applyExceptionsToControlSummaries(
 controlSummaries reportsummary.ControlSummaries,
 exceptionPolicies []armotypes.PostureExceptionPolicy,
+clusterName string,
 ) {
@@
-if !hasExplicitControlException(exceptionPolicies, controlID) {
+if !hasExplicitControlException(exceptionPolicies, controlID, clusterName) {
 continue
 }
@@
-func hasExplicitControlException(exceptionPolicies []armotypes.PostureExceptionPolicy, controlID string) bool {
+func hasExplicitControlException(exceptionPolicies []armotypes.PostureExceptionPolicy, controlID, clusterName string) bool {
 for _, policy := range exceptionPolicies {
+if len(policy.Resources) == 0 {
+continue
+}
 for _, pp := range policy.PosturePolicies {
-if strings.EqualFold(pp.ControlID, controlID) {
-return true
+if !strings.EqualFold(pp.ControlID, controlID) {
+continue
+}
+for _, resource := range policy.Resources {
+designatorCluster := resource.GetCluster()
+if designatorCluster == "" {
+continue
+}
+matched, err := regexp.MatchString("^"+designatorCluster+"$", clusterName)
+if err == nil && matched {
+return true
+}
 }
 }
 }
 return false
 }
```

That keeps the `empty posturePolicies != match all` safeguard, but still prevents a `prod`-scoped exception from turning a `dev` manual control into `passed + w/exceptions`.

If you want full parity with the regular exception path, extracting the existing designator matching from `GetResourceExceptions(..., clusterName)` into a shared helper would be even better than duplicating the cluster check inline.

**Comment by RohanKaran** [comment]
> I think the remaining gap is that the manual-control path no longer preserves the normal `Resources` / `clusterName` scoping. Right now any exception that explicitly names a manual control ID will flip it, even if the designator only targets a different cluster.

> That keeps the `empty posturePolicies != match all` safeguard, but still prevents a `prod`-scoped exception from turning a `dev` manual control into `passed + w/exceptions`.
> 
> If you want full parity with the regular exception path, extracting the existing designator matching from `GetResourceExceptions(..., clusterName)` into a shared helper would be even better than duplicating the cluster check inline.
---
@matthyx I see. I initially assumed manual controls have no real resource attached, making them an org-level thing by looking at the rule definition as the `k8sObject` is always empty. But I guess it makes sense at the cluster level, the requirement might be satisfied on prod-cluster but not on dev-cluster. I'll go ahead and make those changes.

**Comment by RohanKaran** [comment]
@matthyx from suggested changes, moved the `len(policy.Resources) == 0` check inside the `PosturePolicies` loop (after the control ID match). If it stays above the loop, a policy with no resources but a different control ID would incorrectly return true for any control. 

Also used `processor.MatchesCluster` the cluster-matching shared helper, which comes from this opa-utils PR: kubescape/opa-utils#165

Let me know if any further changes are needed.

**Review by matthyx — CHANGES_REQUESTED** [review]
Re-reviewed the latest commit. Still requesting changes: go test ./core/pkg/opaprocessor/... fails because processor.MatchesCluster is not part of exceptions.Processor. Even after that build fix, the new manual-control matcher still only checks cluster scope and ignores the rest of policy.Resources, so namespace/name/label-scoped exceptions can exempt a control too broadly. It also narrows controlID matching to exact case-insensitive equality, while the existing exception path supports exact-or-regex control ID matching.

**Comment by RohanKaran** [comment]
@matthyx The core issue is that we need a reliable way to identify when an exception has no resource-scoped constraints (namespace/name/labels) so we only flip the summary for those cases. We could add an `IsClusterScoped()` method that returns true only when no resource-level constraints (namespace, name, kind, labels etc.) are set. Then in `hasExplicitControlException` we skip any designator where `IsClusterScoped()` is false, since there's nothing to match those constraints against. Does this direction make sense or do you have a preferred approach?

**Comment by RohanKaran** [comment]
Another approach: before flipping the summary in `applyExceptionsToManualControls`, check if any resource in `ResourcesResult` has this control with `skipped+manual review` status. If yes, we skip the summary flip.

For current manual controls with no real resources, `ResourcesResult` has no entries for the control so the check passes and the flip proceeds as normal which the current code already does.
Does this sound like a cleaner approach @matthyx ?

**Comment by matthyx** [comment]
> @matthyx The core issue is that we need a reliable way to identify when an exception has no resource-scoped constraints (namespace/name/labels) so we only flip the summary for those cases. We could add an `IsClusterScoped()` method that returns true only when no resource-level constraints (namespace, name, kind, labels etc.) are set. Then in `hasExplicitControlException` we skip any designator where `IsClusterScoped()` is false, since there's nothing to match those constraints against. Does this direction make sense or do you have a preferred approach?

allow only no-Resources or cluster/global-only designators; return false for namespace/name/kind/labels/path/resourceID/WLID-style selectors, keep regex controlID matching, and either keep the helper local in this PR or bump the dependency together

**Comment by RohanKaran** [comment]
@matthyx Implemented the discussed changes. This depends on kubescape/opa-utils#165 for the MatchesCluster, RegexCompareControlID. Happy to iterate further if anything needs adjusting.

**Review by matthyx — CHANGES_REQUESTED** [review]
Checked again on a2b03cb. With github.com/kubescape/opa-utils temporarily replaced to the opa-utils#165 branch, go test ./core/pkg/opaprocessor/... passes and the manual-control matching logic now looks reasonable to me. The remaining blocker is integration: this PR still calls Processor.MatchesCluster / Processor.RegexCompareControlID from open kubescape/opa-utils#165, while go.mod here still pins github.com/kubescape/opa-utils v0.0.288, so the kubescape branch does not build standalone today. Once that dependency is merged and this PR is updated to consume it (or otherwise wired in), I do not see another blocker in this package.

**Comment by RohanKaran** [comment]
Bumped the version of github.com/kubescape/opa-utils to v0.0.293
- [x] New and existing unit tests pass locally with my changes

**Review by matthyx — APPROVED** [review]
Checked again after the opa-utils bump. The PR now builds cleanly against github.com/kubescape/opa-utils v0.0.293, the manual-control exception matching logic looks sound, and the targeted package tests I ran passed.

**Review by matthyx — APPROVED** [review]
thanks @RohanKaran !
