### PR TITLE
move context flag to root

### LINKED ISSUE #1365: --kube-context flag failed when run "scan framework"
# Description
--kube-context no use if run scan with specific framework

# Environment
OS:  Ubuntu 22.04 LTS
Version: v2.3.8

### PR DESCRIPTION
**Pull request by Daniel-GrunbergerCA**
Fix `--kube-context` flag by making it available to the root command, and move all initialization logic to `PreRun`

fixes #1365

### CODE REVIEW

File: cmd/scan/scan.go [hunk 1]
```diff
@@ -63,17 +62,12 @@ func GetScanCommand(ks meta.IKubescape) *cobra.Command {
...
-			k8sinterface.SetClusterContextName(scanInfo.KubeContext)
-
-		},
 		PostRun: func(cmd *cobra.Command, args []string) {
 			// TODO - revert context
 		},
 	}
 
 	scanCmd.PersistentFlags().StringVarP(&scanInfo.AccountID, "account", "", "", "Kubescape SaaS account ID. Default will load account ID from cache")
-	scanCmd.PersistentFlags().StringVarP(&scanInfo.KubeContext, "kube-context", "", "", "Kube context. Default will use the current-context")
```
Comment (dwertent) [inline cmd/scan/scan.go:76]: Remove the `KubeContext` from the scanInfo object.
(make sure you update the httphandler pkg as well)

**Review by dwertent — CHANGES_REQUESTED** [review]

File: cmd/scan/scan.go (hunk 1 above)
Comment (Daniel-GrunbergerCA) [reply cmd/scan/scan.go:76]: I didn't remove it since I see it comes from the request. How will this be passed to the httphandler?

Comment (dwertent) [reply cmd/scan/scan.go:76]: The httphandler should not receive it from a request because it should scan the cluster it is running in...

**Review by dwertent — APPROVED** [review]
