### PR TITLE
Fix missing upstream panic

### LINKED ISSUE #1005: Kubescape panics when scanning a local Git branch without an upstream and `origin` fallback
# Describe the bug

Kubescape panics on scanning a local git branch when the branch does not have a remote set and a fallback remote named `origin` is missing.

# Environment

OS: Ubuntu 22.04 LTS
Version: git `master`, latest release

# Steps To Reproduce

1. Run the following commands:
```
git clone https://github.com/kubescape/kubscape
cd kubescape
make all
git checkout -b new-branch
git remote rename origin upstream
./kubescape scan examples/
```
2. Observe.

# Expected behavior

Kubescape reports that the origin is missing, and then performs a scan and reports its results as usual.

# Actual Behavior

Kubescape panics as follows:
```
$ ./kubescape scan examples/
[info] Kubescape scanner starting
[warning] unknown build number, this might affect your scan results. Please make sure you are updated to latest version
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x3195f6f]

goroutine 1 [running]:
github.com/kubescape/kubescape/v2/core/cautils.(*LocalGitRepository).GetRemoteUrl(0xc001825680)
        /home/user/kubescape/kubescape/core/cautils/localgitrepository.go:82 +0x1af
github.com/kubescape/kubescape/v2/core/cautils.metadataGitLocal({0x7fff899740ee?, 0x9?})
        /home/user/kubescape/kubescape/core/cautils/scaninfo.go:387 +0x90
github.com/kubescape/kubescape/v2/core/cautils.setContextMetadata(0xc001387540, {0x7fff899740ee, 0x9})
        /home/user/kubescape/kubescape/core/cautils/scaninfo.go:345 +0x37c
github.com/kubescape/kubescape/v2/core/cautils.scanInfoToScanMetadata(0xc0003d6b40)
        /home/user/kubescape/kubescape/core/cautils/scaninfo.go:276 +0x2d9
github.com/kubescape/kubescape/v2/core/cautils.NewOPASessionObj({0x0, 0x0, 0x0}, 0x0, 0xc0003d6b40)
        /home/user/kubescape/kubescape/core/cautils/datastructures.go:51 +0x85
github.com/kubescape/kubescape/v2/core/pkg/policyhandler.(*PolicyHandler).CollectResources(0xc000b1f7f0, {0xc0002d4e00, 0x6, 0x8}, 0xc0003d6b40)
        /home/user/kubescape/kubescape/core/pkg/policyhandler/handlenotification.go:37 +0x3f
github.com/kubescape/kubescape/v2/core/core.(*Kubescape).Scan(0x3c52d00?, 0xc0003d6b40)
        /home/user/kubescape/kubescape/core/core/scan.go:158 +0x6b9
github.com/kubescape/kubescape/v2/cmd/scan.getFrameworkCmd.func2(0x36cc8a0?, {0xc000479620, 0x2, 0x2})
        /home/user/kubescape/kubescape/cmd/scan/framework.go:106 +0x46c
github.com/kubescape/kubescape/v2/cmd/scan.GetScanCommand.func1(0xc0004d8600?, {0xc000429870, 0x1, 0x1?})
        /home/user/kubescape/kubescape/cmd/scan/scan.go:46 +0x166
github.com/spf13/cobra.(*Command).ValidateArgs(...)
        /home/vklokun/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1072
github.com/spf13/cobra.(*Command).execute(0xc0004d8600?, {0xc0004297d0?, 0x1?, 0x1?})
        /home/vklokun/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:885 +0x653
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004d8300)
        /home/vklokun/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vklokun/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/kubescape/kubescape/v2/cmd.Execute()
        /home/user/kubescape/kubescape/cmd/root.go:87 +0x2d
main.main()
        /home/user/kubescape/kubescape/main.go:9 +0x1d
```

# Additional context

This happens because we don’t check if a key is present when accessing the git config `Remotes` field in `localgitrepository.go:82`.

### PR DESCRIPTION
**Pull request by vladklokun**
## Describe your changes

This change fixes the case in which Kubescape would panic when scanning a local Git repository that:
- has the current branch that does not have an upstream set
- does not have an `origin` branch to fall back on

The panic happened because we did not check if the `origin` key exists in the map of upstreams. This change adds a test for this scenario and makes it pass by checking if the key exists. If it does not, it returns an error.

## This PR fixes:

* Resolved #1005 

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

File: core/pkg/resourcehandler/remotegitutils.go [hunk 1]
```diff
@@ -40,7 +40,7 @@ func isGitTokenPresent(gitURL giturl.IGitAPI) bool {
 
 // Get the error message according to the provider
 func getProviderError(gitURL giturl.IGitAPI) error {
-	switch gitURL.GetProvider(){
+	switch gitURL.GetProvider() {
```
Comment (matthyx) [inline core/pkg/resourcehandler/remotegitutils.go:43]: are these needed to fix linting? can we have a separate commit for all formatting related changes?

**Review by amirmalka — APPROVED** [review]

File: core/pkg/resourcehandler/remotegitutils.go (hunk 1 above)
Comment (vladklokun) [reply core/pkg/resourcehandler/remotegitutils.go:43]: Yes, they are. And we do have a separate commit for that inside this pull request :)

**Review by dwertent — APPROVED** [review]
