### PR TITLE
Fix/conditional build for git support

### LINKED ISSUE #964: Wrap the `git2go` dependency
## Problem
Kubescape has the `git2go` dependency, this is for extracting the file commit metadata when scanning repositories.
This dependency requires a non-trivial installation and makes the whole process of building locally more complicated.

## Proposed Solution
The usage of this dependency should be wrapped with a build flag so the `git2go` will be included only when the flag is specified.

### PR DESCRIPTION
**Pull request by fredbi**
### Motivation
The motivation for this change is essentially to make kubescape go-gettable and foster adoption: a simple "go install" command should bring a user up to speed with most functionality.

Similarly, any new adopter or contributor could just clone the repo and runs the tests. Tests that specifically require the git2go library would be skipped.

### Impacts
 *  isolated the git2go dependency, which is now guarded by a build tag "gitenabled"
 *  similarly, isolated tests that specifically require git2go
    handled errors whenever trying to perform a git scan and the feature is not part of the build. This happens when using   "kubescape scan ." for example. In that case, local git scans are just reported as skipped, with a warning.
  *  adapted the build.py build script and CI test suite to include the build tag
  *  adapter the version command to report about the git feature being part of the build or not

## Screenshots - If Any (Optional)
Local build with tag:
```
./kubescape version
[warning] unknown build number, this might affect your scan results. Please make sure you are updated to latest version
Your current version is:  [git enabled in build: true]

./kubescape scan .  
... // no change
```

Local build without tag:
```
/kubescape version
[warning] unknown build number, this might affect your scan results. Please make sure you are updated to latest version
Your current version is:  [git enabled in build: false]
fred@fred-dev2:~/src/github.com/kubescape/kubescape$ ./kubescape scan .
[info] Kubescape scanner starting
[warning] unknown build number, this might affect your scan results. Please make sure you are updated to latest version
[info] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
[info] Accessing local objects
** [warning] git scan skipped. error: git scan not supported by this build. Build with tag "gitenabled" to enable the git scan feature**
[success] Done accessing local objects
[info] Scanning GitLocal
[success] Done scanning GitLocal
... // rest of output proceeds without error
```
## This PR fixes:

* Resolved #964

## Checklist before requesting a review

- [X] My code follows the style guidelines of this project
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [X] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

### CODE REVIEW

**Comment by fredbi** [comment]
@amirmalka reflecting on this PR, there are a few more things:
* updating README and docs (I'll complete that part last)
* at this stage, the extra-complexity of the extra git submodule & replace in go.mod are not gone yet. Removing things would require more changes. For now, I'd suggest we reach an agreement on the current proposed changes and discuss how to proceed further.

File: cmd/version/version.go [hunk 1]
```diff
@@ -16,7 +16,11 @@ func GetVersionCmd() *cobra.Command {
 		RunE: func(cmd *cobra.Command, args []string) error {
 			v := cautils.NewIVersionCheckHandler()
 			v.CheckLatestVersion(cautils.NewVersionCheckRequest(cautils.BuildNumber, "", "", "version"))
-			fmt.Fprintln(os.Stdout, "Your current version is: "+cautils.BuildNumber)
+			fmt.Fprintf(os.Stdout,
+				"Your current version is: %s [git enabled in build: %t]\n",
```
Comment (dwertent) [inline cmd/version/version.go:20]: I think we should print if git is enabled or not only in debug mode

**Review by dwertent — CHANGES_REQUESTED** [review]

File: cmd/version/version.go [hunk 2]
```diff
@@ -16,7 +16,11 @@ func GetVersionCmd() *cobra.Command {
...
+				cautils.BuildNumber,
+				isGitEnabled(),
```
Comment (dwertent) [inline cmd/version/version.go:22]: We should call the `cautils` package

File: cmd/version/git_native_disabled.go [hunk 3]
```diff
@@ -0,0 +1,7 @@
+//go:build !gitenabled
+
+package version
+
+func isGitEnabled() bool {
```
Comment (dwertent) [inline cmd/version/git_native_disabled.go:5]: This should be in the `cautils` package.
This way we have the checks all in one place.

**Review by dwertent — DISMISSED** [review]

File: cmd/version/version.go (hunk 1 above)
Comment (fredbi) [reply cmd/version/version.go:20]: ok good idea. Doing this

Comment (fredbi) [reply cmd/version/version.go]: kubescape --logger debug version
[warning] unknown build number, this might affect your scan results. Please make sure you are updated to latest version
Your current version is:  
[debug] [git disabled in build]

File: cmd/version/git_native_disabled.go (hunk 3 above)
Comment (fredbi) [reply cmd/version/git_native_disabled.go]: done, pushed

**Comment by dwertent** [comment]
@fredbi Thank you :)
It will take me a day or two for reviewing and testing.

**Comment by fredbi** [comment]
> @fredbi Thank you :) It will take me a day or two for reviewing and testing.

You're welcome. Indeed it is difficult to embed conclusive unit tests with the PR for this build. I have been able to verify the "go install" part from my fork.

File: core/pkg/resourcehandler/filesloader.go [hunk 4]
```diff
@@ -131,7 +132,12 @@ func getResourcesFromPath(path string) (map[string]reporthandling.Source, []work
 
 		var lastCommit reporthandling.LastCommit
 		if gitRepo != nil {
-			commitInfo, _ := gitRepo.GetFileLastCommit(source)
+			commitInfo, err := gitRepo.GetFileLastCommit(source)
+			if err != nil && !warnIssued {
```
Comment (matthyx) [inline core/pkg/resourcehandler/filesloader.go:136]: I think here we should check the error type, because in the future we might have different reasons for failing

File: build.py [hunk 5]
```diff
@@ -56,15 +56,15 @@ def main():
         ldflags += " -X {}={}".format(build_url, release_version)
     if client_name:
         ldflags += " -X {}={}".format(client_var, client_name)
- 
-    build_command = ["go", "build", "-buildmode=pie", "-tags=static", "-o", ks_file, "-ldflags" ,ldflags]
+
+    build_command = ["go", "build", "-buildmode=pie", "-tags=static,gitenabled", "-o", ks_file, "-ldflags" ,ldflags]
```
Comment (matthyx) [inline build.py:60]: Please also add `gitenabled` to tags inside the Makefile. Otherwise `make all` does all the work for git2go, but builds without it...

**Comment by matthyx** [comment]
> In that case, local git scans are just reported as skipped, with a warning.

I think we should take a different approach here, I mean still perform the check and either:
- don't submit the results to Kubescape SaaS
- replace missing commit information with dummy placeholders

File: core/pkg/resourcehandler/filesloader.go (hunk 4 above)
Comment (fredbi) [reply core/pkg/resourcehandler/filesloader.go:136]: @matthyx I agree. However, I've attempted to percolate changes gradually: this PR focuses only on supporting a working build without full git support. IMHO, the suggested change (which I agree with) should be deferred to another PR.

Comment (matthyx) [reply core/pkg/resourcehandler/filesloader.go:136]: fair enough... let's do it in a follow up

**Comment by matthyx** [comment]
> > In that case, local git scans are just reported as skipped, with a warning.
> 
> I think we should take a different approach here, I mean still perform the check and either:
> 
> * don't submit the results to Kubescape SaaS
> * replace missing commit information with dummy placeholders

same here, feel free to leave that for later
thanks for your work so far!
can you just fix the Makefile and squash before I merge?

**Comment by fredbi** [comment]
@matthyx 
>   don't submit the results to Kubescape SaaS
>   replace missing commit information with dummy placeholders

Maybe. The primary intent with that PR was to alleviate the "turn-off" effect of a complex build for early adopters/contributors. Official releases would of course always remain built with git support.

But ok to consider that for a follow-up (also see my comment in the issue re follow-ups)

**Review by matthyx — APPROVED** [review]
I'll update the README. Thanks @fredbi !

**Comment by matthyx** [comment]
@dwertent can you close your requested changes and merge?
